micronaut:
  application:
    name: playerModule
  server:
    port: 8082
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET_SPACE_MMO}"'

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'marowak.dev.model'
flyway:
  datasources:
    default:
      enabled: true

jooq:
  datasources:
    default:
      properties:
        hibernate:
          hbm2ddl:
            auto: update
          show_sql: true
      sql-dialect: 'POSTGRES'

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/space_mmo'
    username: 'manager'
    password: 'manager'
    driverClassName: 'org.postgresql.Driver'
    hikari:
      pool-name: ca-pool
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      validation-timeout: 50000