version: "3.9"
services:
  mmo_server:
    image: postgres:15.1
    depends_on:
      - "mongo_db"
    environment:
      - POSTGRES_DB=${SPACE_MMO_POSTGRES_DB_URL}
      - POSTGRES_USER=${SPACE_MMO_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${SPACE_MMO_POSTGRES_DB_PASS}
      - PGDATA=/var/lib/pgsql_docker/data
    ports:
      - "5432:5432"

  mongo_db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${SPACE_MMO_MONGO_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${SPACE_MMO_MONGO_DB_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mongodata: