micronaut:
  application:
    name: playerModule
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET_SPACE_MMO}"'

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'marowak.dev.model'
flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5433/space_mmo_auth'
    username: 'manager'
    password: 'manager'
    driverClassName: 'org.postgresql.Driver'

kafka:
  bootstrap:
    servers: localhost:9092