micronaut:
  application:
    name: playerModule
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_SECRET_SPACE_MMO}"'

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'marowak.dev.model'
flyway:
  datasources:
    default:
      enabled: true

datasources:
  default:
    url: 'jdbc:postgresql://localhost:5432/space_mmo'
    username: 'manager'
    password: 'manager'
    driverClassName: 'org.postgresql.Driver'
    hikari:
      pool-name: ca-pool
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      validation-timeout: 50000

mongodb:
  uri: mongodb://manager:manager@localhost:27017
  options:
    maxConnectionIdleTime: 10000
    readConcern: majority
  cluster:
    maxWaitQueueSize: 5
  connectionPool:
    maxSize: 20

player-character-db:
  name: "space_mmo_character"
  collection: "characters"
