micronaut:
  application:
    name: playerModule
  server:
    port: 8082

kafka:
  bootstrap:
    servers: localhost:9092

jackson:
  serializationInclusion: ALWAYS

physic:
  speed:
    limit: 1200
