micronaut:
  application:
    name: playerModule
  server:
    port: 8082
  packages:
    - marowak

kafka:
  bootstrap:
    servers: localhost:9092

jackson:
  serializationInclusion: ALWAYS

world:
  speed:
    limit: 1200

mock-state-enabled: true