package marowak.dev.enums;

public enum ReceiveCommandType {
    CMD_GET_CHARACTER,
    CMD_GET_INVENTORY,
    CMD_UPDATE_MOTION,
    CMD_LEAVING_PLAYER,
    CMD_UPDATE_INVENTORY_ITEM,
    CMD_UPDATE_SHOOTING,
    CMD_BLOW_UP_CHARACTER,
}
