package marowak.dev.enums;

public enum SendCommandType {
    CMD_RECEIVE_CHARACTER,
    CMD_RECEIVE_INVENTORY,
    CMD_RECEIVE_SPACE_OBJECTS,
    CMD_RECEIVE_UPDATE_INVENTORY_ITEM,
    CMD_RECEIVE_WEAPON_INFO,
    CMD_LEAVING_PLAYER,
    CMD_BLOW_UP_CHARACTER,
    CMD_RECEIVE_ITEM,
    CMD_ERROR,
}
