package marowak.dev.enums;

public enum SendCommandType {
    CMD_GET_INVENTORY, CMD_UPDATE_MOTION, CMD_UPDATE_INVENTORY_ITEM, CMD_UPDATE_SHOOTING, CMD_LEAVING_PLAYER, CMD_BLOW_UP_CHARACTER, CMD_RECEIVE_CHARACTER
}
