micronaut:
  application:
    name: storageModule
  server:
    port: 8083

netty:
  default:
    allocator:
      max-order: 3

jpa:
  default:
    entity-scan:
      classpath: true
      packages:
        - 'marowak.dev.entity'

r2dbc:
  datasources:
    default:
      url: 'r2dbc:postgresql://localhost:5432/space_mmo_storage'
      username: 'manager'
      password: 'manager'
      driverClassName: 'org.postgresql.Driver'

datasources:
  jdbc:
    url: 'jdbc:postgresql://localhost:5432/space_mmo_storage'
    username: 'manager'
    password: 'manager'
    driverClassName: 'org.postgresql.Driver'

flyway:
  datasources:
    jdbc:
      enabled: true
      locations: classpath:db/migration
      username: 'manager'
      password: 'manager'
      url: 'jdbc:postgresql://localhost:5432/space_mmo_storage'

kafka:
  bootstrap:
    servers: localhost:9092
