micronaut:
  application:
    name: storageModule
  server:
    port: 8083
r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: H2
netty:
  default:
    allocator:
      max-order: 3
